var tagsUrl = {
  "merrychristmas": "merry-christmas",
  "gloryhole": "glory-hole",
  "college-(18+)": "college-18",
  "school-(18+)": "school-18",
  "teen-(18+)": "teen-18",
  "sexoadulto": "sexo-adulto",
  "sexoanal": "sexo-anal",
  "paugrande": "pau-grande",
  "bate-papoporvídeonu": "bate-papoporvideonu",
  "Âncora": "ancora",
  "boa-aparência": "boa-aparencia",
  "adereços": "aderecos",
  "masturbação": "masturbacao",
  "bunda-de-pêssego": "bunda-de-pessego",
  "secretário": "secretario",
  "bêbado": "bebado",
  "empregada-doméstica": "empregada-domestica",
  "irmã-mais-velha": "irma-mais-velha",
  "dupla-penetração": "dupla-penetracao",
  "público": "publico",
  "compilação": "compilacao",
  "aeromoça-de-avião": "aeromoça-de-aviao",
  "vestiário": "vestiario",
  "engraçado": "engracado",
  "música": "musica",
  "massagem-erótica": "massagem-erotica",
  "aborígene": "aborigene",
  "mãe-e-filho": "mae-e-filho",
  "japonês": "japones",
  "ejaculação-precoce": "ejaculacao-precoce",
  "asiático": "asiatico",
  "francês": "frances",
  "mulher-grávida": "mulher-gravida",
  "britânico": "britanico",
  "posições-sexuais": "posicoes-sexuais",
  "boneca-inflável": "boneca-inflavel",
  "romântico": "romantico",
  "fazer-sexo-em-pé": "fazer-sexo-em-pe",
  "transgênero": "transgenero",
  "fundição": "fundicao",
  "granddaughter": "granddaughter",
  "carícia": "caricia",
  "injeção": "injecao",
  "encenação": "encenacao",
  "calça-de-couro": "calca-de-couro",
  "avalokitesvara-sentado-em-lótus": "avalokitesvara-sentado-em-lotus",
  "molho-de-pássaro": "molho-de-passaro",
  "webcamshow": "web-cam-show",
  "sexogay": "sexo-gay",
  "spa-de-óleo-essencial": "spa-de-oleo-essencial",
  "transmissão-ao-vivo-ao-ar-livre": "transmissao-ao-vivo-ao-ar-livre",
  "ereção-matinal": "erecao-matinal",
  "técnico-de-massagem": "tecnico-de-massagem",
  "enorme-quantidade-de-sêmen": "enorme-quantidade-de-semen",
  "alemão": "alemao",
  "incesto-entre-irmãos-e-irmãs": "incesto-entre-irmaos-e-irmas",
  "lgbtq+": "lgbtq",
  "teen(18+)": "teen-18",
  "prematureejaculation": "premature-ejaculation",
  "lickingpussy": "licking-pussy",
  "adolescente(18+)": "adolescente-18",
  "pornoxvideos": "porno-xvideos",
  "青少年(18岁以上)": "青少年-18岁以上",
  "sexo-gay-grátis": "sexo-gay-gratis",
  "trêspessoas": "trespessoas",
  "lésbicas": "lesbicas",
  "sexoviolento": "sexo-violento",
  "livebroadcast": "live-broadcast",
  "malebutt": "male-butt",
  "chuparpênis": "chuparpenis",
  "apenasfãs": "apenasfas",
  "duplapenetração": "duplapenetracao",
  "pênisgordo": "penisgordo",
  "garotão": "garotao",
  "garotocomtesão": "garotocomtesao",
  "transmissão-direta-pela-internet": "transmissao-direta-pela-internet",
  "fendadopênis": "fendadopenis",
  "chupandopênis": "chupandopenis",
  "pênismolhado": "penismolhado",
  "pênisfalsoempacote": "penisfalsoempacote",
  "papaideaçúcar": "papaideacucar",
  "bebêdeaçúcar": "bebedeacucar",
  "remoparacães": "remoparacaes",
  "vídeodeorgasmo": "vídeo-deorgasmo",
  "serviçomasculino": "serviço-masculino",
  "orgasmofeminino": "orgasmo-feminino",
  "agarotadeóculos": "agarotadeóculos",
  "youngwoman": "young-woman",
  "face-sitting": "face-sitting",
  "-reverse-cowgirl":  "reverse-cowgirl",

  "blow job" : "blow-job",
  "Big Tits" : "big-tits",
  "Hardcore" : "hardcore",
  "Cum shot" : "cum-shot",
  "Public" : "public",
  "Ass" : "ass",
  "Handjob" : "handjob",
  "out door" : "out-door",
  "Amateur" : "amateur",
  "Babe" : "babe",
  "young girl" : "young-girl",
  "Big dick" : "big-dick",
  "Muscular" : "muscular",
  "Morning" : "morning",
  "Girlfriend" : "girlfriend",
  "Car" : "car",
  "Goddess" : "goddess",
  "Neighbor" : "neighbor",
  "fake dick" : "fake-dick",
  "Office" : "office",
  "Gym" : "gym",
  "Deepest Throat" : "deepest-throat",
  "Lesbian" : "lesbian",
  "Couple Sex" : "couple-sex",
  "Group" : "group",
  "Big Ass" : "big-ass",
  "Massage" : "massage",
  "Kissing" : "kissing",
  "Step sister" : "step-sister",
  "Smoking" : "smoking",
  "big head" : "big-head",
  "Exercise" : "exercise",
  "VR" : "vr",
  "Cute" : "cute",
  "Brazilian" : "brazilian",
  "European" : "european",
  "Asian" : "asian",
  "Italian" : "italian",
  "Japanese" : "japanese",
  "British" : "british",
  "old movie" : "old-movie",
  "Thai" : "thai",
  "Latina" : "latina",
  "Cum Inside" : "cum-inside",
  "Gay" : "gay",
  "Russian" : "russian",
  "Cuckold" : "cuckold",
  "Pussy Licking" : "pussy-licking",
  "Solo Female" : "solo-female",
  "Classmate" : "classmate",
  "Step Fantasy" : "step-fantasy",
  "Czech" : "czech",
  "Red Head" : "red-head",
  "double penetration" : "double-penetration",
  "Female Orgasm" : "female-orgasm",
  "Small Tits" : "small-tits",
  "Webcam" : "webcam",
  "Rough Sex" : "rough-sex",
  "Masturbation" : "masturbation",
  "Blonde" : "blonde",
  "Oil Massage" : "oil-massage",
  "Gangbang" : "gangbang",
  "French" : "french",
  "Korean" : "korean",
  "Strap On" : "strap-on",
  "College (18+)" : "college-(18+)",
  "Muscular Men" : "muscular-men",
  "African" : "african",
  "School (18+)" : "school-(18+)",
  "Teen (18+)" : "teen-(18+)",
  "POV" : "pov",
  "Fisting" : "fisting",
  "Creampie" : "creampie",
  "MILF" : "milf",
  "Lingerie" : "lingerie",
  "Assfuck" : "assfuck",
  "black hair" : "black-hair",
  "tits job" : "tits-job",
  "tied up" : "tied-up",
  "cheer leader" : "cheer-leader",
  "high heels" : "high-heels",
  "anal plug" : "anal-plug",
  "fuck outside" : "fuck-outside",
  "nice ass" : "nice-ass",
  "Mask" : "mask",
  "Boobs Massage" : "boobs-massage",
  "nipple ring" : "nipple-ring",
  "double pregnant" : "double-pregnant",
  "blind fold" : "blind-fold",
  "Tits Massage" : "tits-massage",
  "tits ring" : "tits-ring",
  "cum In mouth" : "cum-in-mouth",
  "Interracial" : "interracial",
  "fat girl" : "fat-girl",
  "porno xvideos" : "porno-xvideos",
  "Big Black Dick" : "big-black-dick",
  "Shaved Pussy" : "shaved-pussy",
  "deepthroat blow job" : "deepthroat-blow-job",
  "porno anal" : "porno-anal",
  "anal fuck" : "anal-fuck",
  "Swallow" : "swallow",
  "Arab" : "arab",
  "German" : "german",
  "Reality" : "reality",
  "Fetish" : "fetish",
  "HD Porn" : "hd-porn",
  "Turkey" : "turkey",
  "Bisexual Male" : "bisexual-male",
  "Popular With Women" : "popular-with-women",
  "Striptease" : "striptease",
  "Described Video" : "described-video",
  "Canada" : "canada",
  "Live Cam Girls" : "live-cam-girls",
  "Argentinian" : "argentinian",
  "Chinese" : "chinese",
  "Ukraine" : "ukraine",
  "Pissing" : "pissing",
  "tattooed women" : "tattooed-women",
  "Classroom" : "classroom",
  "Transgender" : "transgender",
  "AMADOR" : "amador",
  "Face-sitting" : "face-sitting",
  "Doggystyle" : "doggystyle",
  "porno tube" : "porno-tube",
  "Sucking Cock" : "sucking-cock",
  "porno legenda" : "porno-legenda",
  "porno hub" : "porno-hub",
  "Hotel fuck" : "hotel-fuck",
  "Ass Licking Sex" : "ass-licking-sex",
  "hotel sex" : "hotel-sex",
  "video porno" : "video-porno",
  "Pussy Play" : "pussy-play",
  "GOSTOSA" : "gostosa",
  "Cum-on-face" : "cum-on-face",
  "facial cumshot" : "facial-cumshot",
  "porno amador" : "porno-amador",
  "College Girls" : "college-girls",
  "porno Lesbian" : "porno-lesbian",
  "Lesbo" : "lesbo",
  "Fingering Pussy" : "fingering-pussy",
  "Outdoor Fuck" : "outdoor-fuck",
  "Cock sucking" : "cock-sucking",
  "Masturbating Pussy" : "masturbating-pussy",
  "mouth cum" : "mouth-cum",
  "porno Gay" : "porno-gay",
  "Interracial anal" : "interracial-anal",
  "Interracial Sex" : "interracial-sex",
  "double penetration sex" : "double-penetration-sex",
  "filme porno" : "filme-porno",
  "Whores" : "whores",
  "Party Fuck" : "party-fuck",
  "Real Homemade" : "real-homemade",
  "Two Girls" : "two-girls",
  "Tits Fuck" : "tits-fuck",
  "back packe" : "back-packe",
  "Querida" : "querida",
  "Star" : "star",
  "Atriz" : "atriz",
  "Chinese subtitle" : "chinese-subtitle",
  "Massagem" : "massagem",
  "mais velho" : "mais-velho",
  "lindos seios" : "lindos-seios",
  "black stockings" : "black-stockings",
  "meias pretas" : "meias-pretas",
  "Beleza" : "beleza",
  "Boa aparência" : "boa-aparência",
  "Adereços" : "adereços",
  "seios grandes" : "seios-grandes",
  "Salto alto" : "salto-alto",
  "Seios Pequenos" : "seios-pequenos",
  "big breasts" : "big-breasts",
  "Masturbação" : "masturbação",
  "buceta macia" : "buceta-macia",
  "school beauty" : "school-beauty",
  "oral sex" : "oral-sex",
  "sexo oral" : "sexo-oral",
  "Gozada" : "gozada",
  "bunda de pêssego" : "bunda-de-pêssego",
  "young woman" : "young-woman",
  "long legs" : "long-legs",
  "pernas longas" : "pernas-longas",
  "Funny" : "funny",
  "Depois de" : "depois-de",
  "erotic massage" : "erotic-massage",
  "Royal sister" : "royal-sister",
  "like" : "like-",
  "Boquete" : "boquete",
  "Namorado" : "namorado",
  "Enfermeira" : "enfermeira",
  "homem forte" : "homem-forte",
  "Entregador" : "entregador",
  "Strange" : "strange",
  "beleza da escola" : "beleza-da-escola",
  "Bêbado" : "bêbado",
  "Trabalhar" : "trabalhar",
  "Realidade" : "realidade",
  "Madou" : "madou",
  "Corno" : "corno",
  "Dedilhado" : "dedilhado",
  "close range" : "close-range",
  "empregada doméstica" : "empregada-doméstica",
  "pubic hair" : "pubic-hair",
  "pelos pubianos" : "pelos-pubianos",
  "doggy style" : "doggy-style",
  "estilo cachorrinho" : "estilo-cachorrinho",
  "Licking pussy" : "licking-pussy",
  "irmã mais velha" : "irmã-mais-velha",
  "Pele branca" : "pele-branca",
  "Trio" : "trio",
  "Gozada facial" : "gozada-facial",
  "secretly photographed" : "secretly-photographed",
  "fotografado secretamente" : "fotografado-secretamente",
  "Selfie" : "selfie",
  "Group sex" : "group-sex",
  "Dupla Penetração" : "dupla-penetração",
  "Public" : "public-",
  "Estudantes universitários" : "estudantes-universitários",
  "Público" : "público",
  "bathing center" : "bathing-center",
  "ar livre" : "ar-livre",
  "Orgy" : "orgy",
  "Orgia" : "orgia",
  "Lésbica" : "lésbica",
  "White skin" : "white-skin",
  "Brinquedos" : "brinquedos",
  "American" : "american",
  "Vintage" : "vintage",
  "Fumar" : "fumar",
  "Brunette" : "brunette",
  "Morena" : "morena",
  "Soldier" : "soldier",
  "Soldado" : "soldado",
  "High school student" : "high-school-student",
  "estudante do ensino médio" : "estudante-do-ensino-médio",
  "pau enorme" : "pau-enorme",
  "huge cock" : "huge-cock",
  "best shemale" : "best-shemale",
  "Ebon" : "ebon",
  "Compilation" : "compilation",
  "Compilação" : "compilação",
  "Chest" : "chest",
  "Airline stewardess" : "airline-stewardess",
  "Aeromoça de avião" : "aeromoça-de-avião",
  "sexo em grupo" : "sexo-em-grupo",
  "sex slave" : "sex-slave",
  "Academia" : "academia",
  "locker room" : "locker-room",
  "Exclusive" : "exclusive",
  "Exclusivo" : "exclusivo",
  "Mongolia" : "mongolia",
  "Drugged" : "drugged",
  "pregnant woman" : "pregnant-woman",
  "Music" : "music",
  "College Students" : "college-students",
  "swimming pool" : "swimming-pool",
  "dripping wax" : "dripping-wax",
  "cera pingando" : "cera-pingando",
  "Música" : "música",
  "Hair salon" : "hair-salon",
  "first love" : "first-love",
  "primeiro amor" : "primeiro-amor",
  "Drogado" : "drogado",
  "massagem erótica" : "massagem-erótica",
  "Hatano Yui" : "hatano-yui",
  "Aboriginal" : "aboriginal",
  "Aborígene" : "aborígene",
  "mother and son" : "mother-and-son",
  "mãe e filho" : "mãe-e-filho",
  "escrava sexual" : "escrava-sexual",
  "Mikami Yua" : "mikami-yua",
  "sexual knowledge" : "sexual-knowledge",
  "Conhecimento sexual" : "conhecimento-sexual",
  "Abuso" : "abuso",
  "Enteado" : "enteado",
  "Nozomi Aso" : "nozomi-aso",
  "Premature ejaculation" : "premature-ejaculation",
  "Ejaculação precoce" : "ejaculação-precoce",
  "elder sister" : "elder-sister",
  "family incest" : "family-incest",
  "incesto familiar" : "incesto-familiar",
  "Vietnamese" : "vietnamese",
  "nice body" : "nice-body",
  "Idiota" : "idiota",
  "family sex" : "family-sex",
  "sexo em família" : "sexo-em-família",
  "little boy" : "little-boy",
  "18 years old" : "18-years-old",
  "Behind The Scenes" : "behind-the-scenes",
  "Incondicional" : "incondicional",
  "Asiático" : "asiático",
  "notícias sobre sexo" : "notícias-sobre-sexo",
  "Tokyo Hot" : "tokyo-hot",
  "League of Legends" : "league-of-legends",
  "Maduro" : "maduro",
  "Francês" : "francês",
  "Espanha" : "espanha",
  "Choque de carro" : "choque-de-carro",
  "mulher grávida" : "mulher-grávida",
  "Esquisito" : "esquisito",
  "Britânico" : "britânico",
  "Edison Chen" : "edison-chen",
  "Pegue a amante" : "pegue-a-amante",
  "posições sexuais" : "posições-sexuais",
  "HD video" : "hd-video",
  "Vídeo HD" : "vídeo-hd",
  "hidden camera" : "hidden-camera",
  "câmera escondida" : "câmera-escondida",
  "wine bottle" : "wine-bottle",
  "garrafa de vinho" : "garrafa-de-vinho",
  "Pego tendo um caso" : "pego-tendo-um-caso",
  "Discoteca" : "discoteca",
  "school bullying" : "school-bullying",
  "bullying escolar" : "bullying-escolar",
  "small dick" : "small-dick",
  "pau pequeno" : "pau-pequeno",
  "Fan Bingbing" : "fan-bingbing",
  "Exploring flowers" : "exploring-flowers",
  "Explorando flores" : "explorando-flores",
  "inflatable doll" : "inflatable-doll",
  "boneca inflável" : "boneca-inflável",
  "Sexo violento" : "sexo-violento",
  "sexo na praia" : "sexo-na-praia",
  "Spanish" : "spanish",
  "Brasil" : "brasil",
  "Brasileiro" : "brasileiro",
  "plugue anal" : "plugue-anal",
  "Peach ass" : "peach-ass",
  "fat hole" : "fat-hole",
  "buraco gordo" : "buraco-gordo",
  "Outdoor live broadcast" : "outdoor-live-broadcast",
  "Liu Yue" : "liu-yue",
  "massage technician" : "massage-technician",
  "sex positions" : "sex-positions",
  "singing and dancing" : "singing-and-dancing",
  "Romântico" : "romântico",
  "strike up a conversation" : "strike-up-a-conversation",
  "young girls" : "young-girls",
  "Bangkok" : "bangkok",
  "role play" : "role-play",
  "lick cock" : "lick-cock",
  "vaginal dilator" : "vaginal-dilator",
  "dilatador vaginal" : "dilatador-vaginal",
  "Fazer sexo em pé" : "fazer-sexo-em-pé",
  "Lambendo o cu" : "lambendo-o-cu",
  "Lambendo buceta" : "lambendo-buceta",
  "Homens musculosos" : "homens-musculosos",
  "bondage training" : "bondage-training",
  "treinamento de escravidão" : "treinamento-de-escravidão",
  "Fundição" : "fundição",
  "mulher jovem" : "mulher-jovem",
  "orgasmo feminino" : "orgasmo-feminino",
  "pool party" : "pool-party",
  "festa na piscina" : "festa-na-piscina",
  "Japanese shemale" : "japanese-shemale",
  "Travesti japonesa" : "travesti-japonesa",
  "shopping center" : "shopping-center",
  "Japanese variety show" : "japanese-variety-show",
  "Show de variedades japonesas" : "show-de-variedades-japonesas",
  "street interview" : "street-interview",
  "entrevista de rua" : "entrevista-de-rua",
  "special massage" : "special-massage",
  "massagem especial" : "massagem-especial",
  "Silicone doll" : "silicone-doll",
  "Boneca de silicone" : "boneca-de-silicone",
  "original underwear" : "original-underwear",
  "Impotence and premature ejaculation" : "impotence-and-premature-ejaculation",
  "Thailand" : "thailand",
  "vida noturna" : "vida-noturna",
  "Indian" : "indian",
  "Pattaya" : "pattaya",
  "18 anos de idade" : "18-anos-de-idade",
  "Encenação" : "encenação",
  "Courier" : "courier",
  "urban village" : "urban-village",
  "leather pants" : "leather-pants",
  "calça de couro" : "calça-de-couro",
  "Avalokitesvara sentado em lótus" : "avalokitesvara-sentado-em-lótus",
  "old woman" : "old-woman",
  "slut wife" : "slut-wife",
  "punho anal" : "punho-anal",
  "Sora Aoi" : "sora-aoi",
  "classic movie" : "classic-movie",
  "Korean movies" : "korean-movies",
  "hold and fuck" : "hold-and-fuck",
  "street girl" : "street-girl",
  "Cinta" : "cinta",
  "bird sauce" : "bird-sauce",
  "molho de pássaro" : "molho-de-pássaro",
  "Interactive" : "interactive",
  "Interativo" : "interativo",
  "male male" : "male-male",
  "free gay sex" : "free-gay-sex",
  "tight ass" : "tight-ass",
  "Webcamshow" : "webcamshow",
  "Sexogay" : "sexogay",
  "StrapOn" : "strapon",
  "LGBTQ" : "lgbtq",
  "sex news" : "sex-news",
  "Star Media" : "star-media",
  "Essential oil spa" : "essential-oil-spa",
  "Found to be having an affair" : "found-to-be-having-an-affair",
  "sexual services" : "sexual-services",
  "iniciar uma conversa" : "iniciar-uma-conversa",
  "girl jk" : "girl-jk",
  "Kato Taka" : "kato-taka",
  "Ukrainian" : "ukrainian",
  "Ukrainian beauty" : "ukrainian-beauty",
  "Beleza ucraniana" : "beleza-ucraniana",
  "spa de óleo essencial" : "spa-de-óleo-essencial",
  "Transmissão ao vivo ao ar livre" : "transmissão-ao-vivo-ao-ar-livre",
  "Genshin Impact" : "genshin-impact",
  "Douluo Dalu" : "douluo-dalu",
  "audio and video" : "audio-and-video",
  "nude show" : "nude-show",
  "show de nudez" : "show-de-nudez",
  "Morning erection" : "morning-erection",
  "ereção matinal" : "ereção-matinal",
  "lick asshole" : "lick-asshole",
  "técnico de massagem" : "técnico-de-massagem",
  "lamber pau" : "lamber-pau",
  "steel ball" : "steel-ball",
  "Enorme quantidade de sêmen" : "enorme-quantidade-de-sêmen",
  "Mulher Solitária" : "mulher-solitária",
  "garota de rua" : "garota-de-rua",
  "Late night health room" : "late-night-health-room",
  "Thai ladyboy" : "thai-ladyboy",
  "Public places" : "public-places",
  "public agent" : "public-agent",
  "beautiful boobs" : "beautiful-boobs",
  "anal fisting" : "anal-fisting",
  "Alemão" : "alemão",
  "Parody" : "parody",
  "Paródia" : "paródia",
  "Tcheco" : "tcheco",
  "Incesto entre irmãos e irmãs" : "incesto-entre-irmãos-e-irmãs",
  "big cock" : "big-cock",
  "big dick" : "big-dick",
  "Old/Young(18+)" : "old/young(18+)",
  "Pussy lickLicking pussy" : "pussy-licklicking-pussy",
  "homo sexual" : "homo-sexual",
  "Hot Pussy" : "hot-pussy",
  "porno gay" : "porno-gay",
  "Hot-Pussy" : "hot-pussy",
  "Massage pussy" : "massage-pussy",
  "LGBTQ+" : "lgbtq+",
  "group sex" : "group-sex",
  "Teen(18+)" : "teen(18+)",
  "Prematureejaculation" : "prematureejaculation",
  "gay hots" : "gay-hots",
  "Pussylick" : "pussylick",
  "suckingDick" : "suckingdick",
  "HD video" : "hd-video",
  "Type96" : "type96",
  "Bigtits" : "bigtits",
  "Big pussy" : "big-pussy",
  "big ass" : "big-ass",
  "Lickingpussy" : "lickingpussy",
  "ass fuck" : "ass-fuck",
  "bare fuck" : "bare-fuck",
  "Peachass" : "peachass",
  "rough sex" : "rough-sex",
  "Black person" : "black-person",
  "sexo anal" : "sexo-anal",
  "big boobs" : "big-boobs",
  "beach sex" : "beach-sex",
  "Bissxual" : "bissxual",
  "gay blow job" : "gay-blow-job",
  "hot gay sex" : "hot-gay-sex",
  "boquete gay" : "boquete-gay",
  "Adolescente(18+)" : "adolescente(18+)",
  "Orgasmvideo" : "orgasmvideo",
  "Tipo96" : "tipo96",
  "tattooed women" : "tattooed-women",
  "double penetration" : "double-penetration",
  "japan videos" : "japan-videos",
  "Teacher-studentrelationship" : "teacher-studentrelationship",
  "sex party" : "sex-party",
  "MuscularMen" : "muscularmen",
  "PontodeacupunturaHD" : "pontodeacupunturahd",
  "VídeoHD." : "vídeohd.",
  "sexo gay grátis" : "sexo-gay-grátis",
  "threesome gay" : "threesome-gay",
  "Sexoviolento" : "sexoviolento",
  "coming out" : "coming-out",
  "cum in his mouth" : "cum-in-his-mouth",
  "European-Porn" : "european-porn",
  "thick cum" : "thick-cum",
  "facial cumshot" : "facial-cumshot",
  "transmissão direta pela Internet" : "transmissão-direta-pela-internet",
  "Padrasto" : "padrasto",
  "Jovemcasal" : "jovemcasal",
  "Pênisfalsoempacote" : "pênisfalsoempacote",
  "Tinder" : "tinder",
  "Boqueteduplo" : "boqueteduplo",
  "Quarteto" : "quarteto",
  "Batidadepunheta" : "batidadepunheta",
  "Vídeodeorgasmo" : "vídeodeorgasmo",
  "big pussy" : "big-pussy",
  "quick hand job" : "quick-hand-job",
  "sex slave" : "sex-slave",
  "hold and fuck" : "hold-and-fuck",
  "White skin" : "white-skin",
  "porno brasileiro" : "porno-brasileiro",
  "legenda porno gay" : "legenda-porno-gay",
  "amateur anal" : "amateur-anal",
  "big breasts" : "big-breasts",
  "HD viewing hole" : "hd-viewing-hole",
  "porno grafiade terror" : "porno-grafiade-terror",
  "Pessoanegra" : "pessoanegra",
  "super model" : "super-model",
  "Bucetagostosa." : "bucetagostosa.",
  "naked loans leaked" : "naked-loans-leaked",
  "villa pool" : "villa-pool",
  "up side down sex" : "up-side-down-sex",
  "bare fuck" : "bare-fuck",
  "red head" : "red-head",
  "bate papoporvideonu" : "bate-papoporvideonu",
  "big cock" : "big-cock",
  "black huge cock" : "black-huge-cock",
  "black person" : "black-person",
  "fucking stand" : "fucking-stand",
  "special massage" : "special-massage",
  "erotic massage" : "erotic-massage",
  "Publicplaces" : "publicplaces",
  "Have a conversation outdoors" : "have-a-conversation-outdoors",
  "sexoem grupo" : "sexoem-grupo",
  "sexona praia" : "sexona-praia",
  "ASMR" : "asmr",
  "Agarotadeóculos." : "agarotadeóculos.",
  "small tits" : "small-tits",
  "solo female" : "solo-female",
  "big boobs" : "big-boobs",
  "Pussy lick Licking pussy" : "pussy-lick-licking-pussy",
  "quick hand job" : "quick-hand-job",
  "Special groups" : "special-groups",
  "Hot Pussy" : "hot-pussy",
  "anal fuck" : "anal-fuck",
  "anal plug" : "anal-plug",
  "anal fisting" : "anal-fisting",
  "weird shaped dick" : "weird-shaped-dick",
  "sex sharing" : "sex-sharing",
  "highschool student" : "highschool-student",
  "school beauty" : "school-beauty",
  "old and young" : "old-and-young",
  "sex positions" : "sex-positions",
  "Out door leakage" : "out-door-leakage",
  "secret journey" : "secret-journey",
  "big cockl oli" : "big-cockl-oli",
  "junior high school students" : "junior-high-school-students",
  "step family" : "step-family",
  "locker room" : "locker-room",
  "step daughter" : "step-daughter",
  "public sex" : "public-sex",
  "Germany" : "germany",
  "Arab" : "arab-",
  "Goddess" : "goddess",
  "car sex" : "car-sex",
  "sugar daddy" : "sugar-daddy",
  "tatto men" : "tatto-men",
  "cow girl" : "cow-girl-",
  "face sitting" : "face-sitting",
  "mammary intercourse" : "mammary-intercourse",
  "Brunette" : "brunette-",
  "sex slave" : "sex-slave",
  "double anal dap" : "double-anal-dap",
  "missionary" : "missionary-",
  "reverse cowgirl" : "-reverse-cowgirl",
  "anal gape" : "anal-gape",
  "NTR" : "ntr",
  "couple love" : "couple-love",
  "Ahegao" : "ahegao",
  "asian girl" : "asian-girl",
  "stockings foot" : "stockings-foot",
  "gay anal" : "gay-anal",
  

}



// {
//   // 从 /old-page 重定向到 /new-page，状态码为 301
//   from: '/old-page',
//   to: '/new-page',
//   statusCode: 301
// }

export default function ({ route, redirect, app }) {
  const currentLocale = app.i18n.locale
  const { name, params } = route;
  console.log( 'route', route )
  if( name && name.indexOf("tag-name") != -1 && tagsUrl[params.name] ){
    if( currentLocale != "en" ){
      redirect(301, `/${currentLocale}/tag/${tagsUrl[params.name]}`)
    }else{
      redirect(301, `/tag/${tagsUrl[params.name]}`)
    }
  }
  // 如果路由不匹配任何页面，重定向到当前语言的首页
  if (route.matched.length == 0) {
    redirect(301, `/`)
  }
}